<?php
// Checksum file
// Product: xperience40 - vBExperience
// Version: 4.0.4
// File generated by: $RCSfile: mh_md5gen.php,v $ - $Revision: 2.0.1 $
// Generator: MD5 Version File generator by MarcoH64 and PitchouneN64ngc (c)

$md5_sums = array(
	'/' => array(
		'xperience.php' => 'd0df8b5f5bc3d9b49996cfcd6510d0f0',
	),
	'/admincp' => array(
		'xperience_admin.php' => '56bf5c240284e8196fed6107befb4831',
	),
	'/includes' => array(
		'class_xperience.php' => '78fbc528c9c4f677c4d441319f1de5e5',
		'functions_xperience.php' => '07e3d57da0730590f737bd7019e67200',
		'install_xperience.php' => 'd17daec7ab085780ce16ef793f30d47b',
	),
	'/includes/cron' => array(
		'xperience_achievements.php' => 'bd597d4233376a6d28d0af9d863ca9cf',
		'xperience_activity.php' => 'bed1536e2fa83e66425941f8352b3736',
		'xperience_awards.php' => 'bc0b3626c1fb8a7f9788be2e6e348068',
		'xperience_calc.php' => '4bd0700ddddf056e7126fdedb52e6829',
		'xperience_groups.php' => '9c9735551edaa0949b2632fd23201692',
	),
	'/includes/xml' => array(
		'cpnav_xperience.xml' => '4827983677b7226b3fc5df29b4b55743',
		'hooks_xperience.xml' => '7af44e0a4fc4691e406ef50a53371c00',
	),
	'/xperience/hooks' => array(
		'member_build_blocks_start.php' => '8224feef0e21453c1287be0b21c2b9bc',
		'memberaction_dropdown.php' => '69362cd97a170d34997e70701c6a3ae0',
		'postbit_display_complete.php' => 'd4ca414216eefc60595d6594604391e5',
	),
	'/xperience/widgets' => array(
		'activity.php' => '79573a3233222a407d0139f983bdb2de',
	),
);
$md5_sum_softwareid = 'xperience40';
$md5_sum_versions['xperience40'] = '4.0.4';
?>
